version: "3"

services:
  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - try_gin_paragraph_layout

  php:
    depends_on:
      - db
    build:
      context: ./.boing/docker/php
      args:
        GD_REQUIRE: 1
    volumes:
      - .:/srv
    networks:
      - try_gin_paragraph_layout

  web:
    depends_on:
      - php
    build:
      context: ./.boing/docker/nginx/drupal
    volumes:
      - .:/srv
    networks:
      - try_gin_paragraph_layout

networks:
  try_gin_paragraph_layout:
    external: true

volumes:
  db_data:
